### ISSUE TITLE
При сжимании экрана едет верстка или центрирование элементов

### ISSUE THREAD

**Issue by vladimixz** [Yehor0110/yehor0110.github.io#2]
https://prnt.sc/ydzoch
https://prnt.sc/ydztj4
https://prnt.sc/ydzv8v
https://prnt.sc/ydzyz6

**Comment by Yehor0110** [comment]
@vladimixz  
Добавил мобильную версию, всё работает. 
Вот только после подключения SASS консоль начала ругаться и теперь не могу перейти по своему адресу 
Project is running at http://192.168.1.3/
работает только http://localhost:3000/

ругается на:
 node_modules/react-refresh/cjs/react-refresh-runtime.development.js
 node_modules/react-refresh/runtime.js
и на webpack ругался

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
Compiling...
Compiled with warnings.
